# Keycloak Handlers
# These are tasks triggered by notify

---
- name: Restart Keycloak container
  community.docker.docker_container:
    name: "{{ keycloak_container }}"
    state: started
  become: true

- name: Restart backend container
  community.docker.docker_container:
    name: "{{ backend_container }}"
    state: started
  become: true