# Keycloak role - variables

---
keycloak_realm: attendance-app
keycloak_url: http://keycloak:8080
keycloak_admin_user: admin
keycloak_admin_password: admin
keycloak_client_id: backend-client
keycloak_client_secret: best-practice-secret-12345
keycloak_container: infra-keycloak-1