# Use the official MinIO image as the base
FROM quay.io/minio/minio:latest

# Set the command to start the MinIO server with the console address
CMD ["server", "/data", "--console-address", ":9001"]

