"""
Redmine-compatible timezone list.

Mirrors ActiveSupport::TimeZone — the same list Redmine shows in its
user preferences dropdown. Stored here as a static constant since
this list only changes with Rails/Redmine version upgrades.

Each entry:
  value  — Redmine's internal timezone identifier (e.g. "New Delhi")
  label  — human-readable with GMT offset (e.g. "(GMT+05:30) New Delhi")
  offset — just the offset string (e.g. "+05:30")
"""

REDMINE_TIMEZONES = [
    {"value": "International Date Line West", "label": "(GMT-12:00) International Date Line West", "offset": "-12:00"},
    {"value": "American Samoa", "label": "(GMT-11:00) American Samoa", "offset": "-11:00"},
    {"value": "Midway Island", "label": "(GMT-11:00) Midway Island", "offset": "-11:00"},
    {"value": "Hawaii", "label": "(GMT-10:00) Hawaii", "offset": "-10:00"},
    {"value": "Alaska", "label": "(GMT-09:00) Alaska", "offset": "-09:00"},
    {"value": "Pacific Time (US & Canada)", "label": "(GMT-08:00) Pacific Time (US & Canada)", "offset": "-08:00"},
    {"value": "Tijuana", "label": "(GMT-08:00) Tijuana", "offset": "-08:00"},
    {"value": "Arizona", "label": "(GMT-07:00) Arizona", "offset": "-07:00"},
    {"value": "Mazatlan", "label": "(GMT-07:00) Mazatlan", "offset": "-07:00"},
    {"value": "Mountain Time (US & Canada)", "label": "(GMT-07:00) Mountain Time (US & Canada)", "offset": "-07:00"},
    {"value": "Central America", "label": "(GMT-06:00) Central America", "offset": "-06:00"},
    {"value": "Central Time (US & Canada)", "label": "(GMT-06:00) Central Time (US & Canada)", "offset": "-06:00"},
    {"value": "Chihuahua", "label": "(GMT-06:00) Chihuahua", "offset": "-06:00"},
    {"value": "Guadalajara", "label": "(GMT-06:00) Guadalajara", "offset": "-06:00"},
    {"value": "Mexico City", "label": "(GMT-06:00) Mexico City", "offset": "-06:00"},
    {"value": "Monterrey", "label": "(GMT-06:00) Monterrey", "offset": "-06:00"},
    {"value": "Saskatchewan", "label": "(GMT-06:00) Saskatchewan", "offset": "-06:00"},
    {"value": "Bogota", "label": "(GMT-05:00) Bogota", "offset": "-05:00"},
    {"value": "Eastern Time (US & Canada)", "label": "(GMT-05:00) Eastern Time (US & Canada)", "offset": "-05:00"},
    {"value": "Indiana (East)", "label": "(GMT-05:00) Indiana (East)", "offset": "-05:00"},
    {"value": "Lima", "label": "(GMT-05:00) Lima", "offset": "-05:00"},
    {"value": "Quito", "label": "(GMT-05:00) Quito", "offset": "-05:00"},
    {"value": "Atlantic Time (Canada)", "label": "(GMT-04:00) Atlantic Time (Canada)", "offset": "-04:00"},
    {"value": "Caracas", "label": "(GMT-04:00) Caracas", "offset": "-04:00"},
    {"value": "Georgetown", "label": "(GMT-04:00) Georgetown", "offset": "-04:00"},
    {"value": "La Paz", "label": "(GMT-04:00) La Paz", "offset": "-04:00"},
    {"value": "Puerto Rico", "label": "(GMT-04:00) Puerto Rico", "offset": "-04:00"},
    {"value": "Santiago", "label": "(GMT-04:00) Santiago", "offset": "-04:00"},
    {"value": "Newfoundland", "label": "(GMT-03:30) Newfoundland", "offset": "-03:30"},
    {"value": "Brasilia", "label": "(GMT-03:00) Brasilia", "offset": "-03:00"},
    {"value": "Buenos Aires", "label": "(GMT-03:00) Buenos Aires", "offset": "-03:00"},
    {"value": "Montevideo", "label": "(GMT-03:00) Montevideo", "offset": "-03:00"},
    {"value": "Greenland", "label": "(GMT-02:00) Greenland", "offset": "-02:00"},
    {"value": "Mid-Atlantic", "label": "(GMT-02:00) Mid-Atlantic", "offset": "-02:00"},
    {"value": "Azores", "label": "(GMT-01:00) Azores", "offset": "-01:00"},
    {"value": "Cape Verde Is.", "label": "(GMT-01:00) Cape Verde Is.", "offset": "-01:00"},
    {"value": "Edinburgh", "label": "(GMT+00:00) Edinburgh", "offset": "+00:00"},
    {"value": "Lisbon", "label": "(GMT+00:00) Lisbon", "offset": "+00:00"},
    {"value": "London", "label": "(GMT+00:00) London", "offset": "+00:00"},
    {"value": "Monrovia", "label": "(GMT+00:00) Monrovia", "offset": "+00:00"},
    {"value": "UTC", "label": "(GMT+00:00) UTC", "offset": "+00:00"},
    {"value": "Amsterdam", "label": "(GMT+01:00) Amsterdam", "offset": "+01:00"},
    {"value": "Belgrade", "label": "(GMT+01:00) Belgrade", "offset": "+01:00"},
    {"value": "Berlin", "label": "(GMT+01:00) Berlin", "offset": "+01:00"},
    {"value": "Bern", "label": "(GMT+01:00) Bern", "offset": "+01:00"},
    {"value": "Bratislava", "label": "(GMT+01:00) Bratislava", "offset": "+01:00"},
    {"value": "Brussels", "label": "(GMT+01:00) Brussels", "offset": "+01:00"},
    {"value": "Budapest", "label": "(GMT+01:00) Budapest", "offset": "+01:00"},
    {"value": "Casablanca", "label": "(GMT+01:00) Casablanca", "offset": "+01:00"},
    {"value": "Copenhagen", "label": "(GMT+01:00) Copenhagen", "offset": "+01:00"},
    {"value": "Dublin", "label": "(GMT+01:00) Dublin", "offset": "+01:00"},
    {"value": "Ljubljana", "label": "(GMT+01:00) Ljubljana", "offset": "+01:00"},
    {"value": "Madrid", "label": "(GMT+01:00) Madrid", "offset": "+01:00"},
    {"value": "Paris", "label": "(GMT+01:00) Paris", "offset": "+01:00"},
    {"value": "Prague", "label": "(GMT+01:00) Prague", "offset": "+01:00"},
    {"value": "Rome", "label": "(GMT+01:00) Rome", "offset": "+01:00"},
    {"value": "Sarajevo", "label": "(GMT+01:00) Sarajevo", "offset": "+01:00"},
    {"value": "Skopje", "label": "(GMT+01:00) Skopje", "offset": "+01:00"},
    {"value": "Stockholm", "label": "(GMT+01:00) Stockholm", "offset": "+01:00"},
    {"value": "Vienna", "label": "(GMT+01:00) Vienna", "offset": "+01:00"},
    {"value": "Warsaw", "label": "(GMT+01:00) Warsaw", "offset": "+01:00"},
    {"value": "West Central Africa", "label": "(GMT+01:00) West Central Africa", "offset": "+01:00"},
    {"value": "Zagreb", "label": "(GMT+01:00) Zagreb", "offset": "+01:00"},
    {"value": "Zurich", "label": "(GMT+01:00) Zurich", "offset": "+01:00"},
    {"value": "Athens", "label": "(GMT+02:00) Athens", "offset": "+02:00"},
    {"value": "Bucharest", "label": "(GMT+02:00) Bucharest", "offset": "+02:00"},
    {"value": "Cairo", "label": "(GMT+02:00) Cairo", "offset": "+02:00"},
    {"value": "Harare", "label": "(GMT+02:00) Harare", "offset": "+02:00"},
    {"value": "Helsinki", "label": "(GMT+02:00) Helsinki", "offset": "+02:00"},
    {"value": "Jerusalem", "label": "(GMT+02:00) Jerusalem", "offset": "+02:00"},
    {"value": "Kaliningrad", "label": "(GMT+02:00) Kaliningrad", "offset": "+02:00"},
    {"value": "Kyiv", "label": "(GMT+02:00) Kyiv", "offset": "+02:00"},
    {"value": "Pretoria", "label": "(GMT+02:00) Pretoria", "offset": "+02:00"},
    {"value": "Riga", "label": "(GMT+02:00) Riga", "offset": "+02:00"},
    {"value": "Sofia", "label": "(GMT+02:00) Sofia", "offset": "+02:00"},
    {"value": "Tallinn", "label": "(GMT+02:00) Tallinn", "offset": "+02:00"},
    {"value": "Vilnius", "label": "(GMT+02:00) Vilnius", "offset": "+02:00"},
    {"value": "Baghdad", "label": "(GMT+03:00) Baghdad", "offset": "+03:00"},
    {"value": "Istanbul", "label": "(GMT+03:00) Istanbul", "offset": "+03:00"},
    {"value": "Kuwait", "label": "(GMT+03:00) Kuwait", "offset": "+03:00"},
    {"value": "Minsk", "label": "(GMT+03:00) Minsk", "offset": "+03:00"},
    {"value": "Moscow", "label": "(GMT+03:00) Moscow", "offset": "+03:00"},
    {"value": "Nairobi", "label": "(GMT+03:00) Nairobi", "offset": "+03:00"},
    {"value": "Riyadh", "label": "(GMT+03:00) Riyadh", "offset": "+03:00"},
    {"value": "St. Petersburg", "label": "(GMT+03:00) St. Petersburg", "offset": "+03:00"},
    {"value": "Volgograd", "label": "(GMT+03:00) Volgograd", "offset": "+03:00"},
    {"value": "Tehran", "label": "(GMT+03:30) Tehran", "offset": "+03:30"},
    {"value": "Abu Dhabi", "label": "(GMT+04:00) Abu Dhabi", "offset": "+04:00"},
    {"value": "Baku", "label": "(GMT+04:00) Baku", "offset": "+04:00"},
    {"value": "Muscat", "label": "(GMT+04:00) Muscat", "offset": "+04:00"},
    {"value": "Samara", "label": "(GMT+04:00) Samara", "offset": "+04:00"},
    {"value": "Tbilisi", "label": "(GMT+04:00) Tbilisi", "offset": "+04:00"},
    {"value": "Yerevan", "label": "(GMT+04:00) Yerevan", "offset": "+04:00"},
    {"value": "Kabul", "label": "(GMT+04:30) Kabul", "offset": "+04:30"},
    {"value": "Almaty", "label": "(GMT+05:00) Almaty", "offset": "+05:00"},
    {"value": "Ekaterinburg", "label": "(GMT+05:00) Ekaterinburg", "offset": "+05:00"},
    {"value": "Islamabad", "label": "(GMT+05:00) Islamabad", "offset": "+05:00"},
    {"value": "Karachi", "label": "(GMT+05:00) Karachi", "offset": "+05:00"},
    {"value": "Tashkent", "label": "(GMT+05:00) Tashkent", "offset": "+05:00"},
    {"value": "Chennai", "label": "(GMT+05:30) Chennai", "offset": "+05:30"},
    {"value": "Kolkata", "label": "(GMT+05:30) Kolkata", "offset": "+05:30"},
    {"value": "Mumbai", "label": "(GMT+05:30) Mumbai", "offset": "+05:30"},
    {"value": "New Delhi", "label": "(GMT+05:30) New Delhi", "offset": "+05:30"},
    {"value": "Sri Jayawardenepura", "label": "(GMT+05:30) Sri Jayawardenepura", "offset": "+05:30"},
    {"value": "Kathmandu", "label": "(GMT+05:45) Kathmandu", "offset": "+05:45"},
    {"value": "Astana", "label": "(GMT+06:00) Astana", "offset": "+06:00"},
    {"value": "Dhaka", "label": "(GMT+06:00) Dhaka", "offset": "+06:00"},
    {"value": "Urumqi", "label": "(GMT+06:00) Urumqi", "offset": "+06:00"},
    {"value": "Rangoon", "label": "(GMT+06:30) Rangoon", "offset": "+06:30"},
    {"value": "Bangkok", "label": "(GMT+07:00) Bangkok", "offset": "+07:00"},
    {"value": "Hanoi", "label": "(GMT+07:00) Hanoi", "offset": "+07:00"},
    {"value": "Jakarta", "label": "(GMT+07:00) Jakarta", "offset": "+07:00"},
    {"value": "Krasnoyarsk", "label": "(GMT+07:00) Krasnoyarsk", "offset": "+07:00"},
    {"value": "Novosibirsk", "label": "(GMT+07:00) Novosibirsk", "offset": "+07:00"},
    {"value": "Beijing", "label": "(GMT+08:00) Beijing", "offset": "+08:00"},
    {"value": "Chongqing", "label": "(GMT+08:00) Chongqing", "offset": "+08:00"},
    {"value": "Hong Kong", "label": "(GMT+08:00) Hong Kong", "offset": "+08:00"},
    {"value": "Irkutsk", "label": "(GMT+08:00) Irkutsk", "offset": "+08:00"},
    {"value": "Kuala Lumpur", "label": "(GMT+08:00) Kuala Lumpur", "offset": "+08:00"},
    {"value": "Perth", "label": "(GMT+08:00) Perth", "offset": "+08:00"},
    {"value": "Singapore", "label": "(GMT+08:00) Singapore", "offset": "+08:00"},
    {"value": "Taipei", "label": "(GMT+08:00) Taipei", "offset": "+08:00"},
    {"value": "Ulaanbaatar", "label": "(GMT+08:00) Ulaanbaatar", "offset": "+08:00"},
    {"value": "Osaka", "label": "(GMT+09:00) Osaka", "offset": "+09:00"},
    {"value": "Sapporo", "label": "(GMT+09:00) Sapporo", "offset": "+09:00"},
    {"value": "Seoul", "label": "(GMT+09:00) Seoul", "offset": "+09:00"},
    {"value": "Tokyo", "label": "(GMT+09:00) Tokyo", "offset": "+09:00"},
    {"value": "Yakutsk", "label": "(GMT+09:00) Yakutsk", "offset": "+09:00"},
    {"value": "Adelaide", "label": "(GMT+09:30) Adelaide", "offset": "+09:30"},
    {"value": "Darwin", "label": "(GMT+09:30) Darwin", "offset": "+09:30"},
    {"value": "Brisbane", "label": "(GMT+10:00) Brisbane", "offset": "+10:00"},
    {"value": "Canberra", "label": "(GMT+10:00) Canberra", "offset": "+10:00"},
    {"value": "Guam", "label": "(GMT+10:00) Guam", "offset": "+10:00"},
    {"value": "Hobart", "label": "(GMT+10:00) Hobart", "offset": "+10:00"},
    {"value": "Melbourne", "label": "(GMT+10:00) Melbourne", "offset": "+10:00"},
    {"value": "Port Moresby", "label": "(GMT+10:00) Port Moresby", "offset": "+10:00"},
    {"value": "Sydney", "label": "(GMT+10:00) Sydney", "offset": "+10:00"},
    {"value": "Vladivostok", "label": "(GMT+10:00) Vladivostok", "offset": "+10:00"},
    {"value": "Magadan", "label": "(GMT+11:00) Magadan", "offset": "+11:00"},
    {"value": "New Caledonia", "label": "(GMT+11:00) New Caledonia", "offset": "+11:00"},
    {"value": "Solomon Is.", "label": "(GMT+11:00) Solomon Is.", "offset": "+11:00"},
    {"value": "Srednekolymsk", "label": "(GMT+11:00) Srednekolymsk", "offset": "+11:00"},
    {"value": "Auckland", "label": "(GMT+12:00) Auckland", "offset": "+12:00"},
    {"value": "Fiji", "label": "(GMT+12:00) Fiji", "offset": "+12:00"},
    {"value": "Kamchatka", "label": "(GMT+12:00) Kamchatka", "offset": "+12:00"},
    {"value": "Marshall Is.", "label": "(GMT+12:00) Marshall Is.", "offset": "+12:00"},
    {"value": "Wellington", "label": "(GMT+12:00) Wellington", "offset": "+12:00"},
    {"value": "Chatham Is.", "label": "(GMT+12:45) Chatham Is.", "offset": "+12:45"},
    {"value": "Nuku'alofa", "label": "(GMT+13:00) Nuku'alofa", "offset": "+13:00"},
    {"value": "Samoa", "label": "(GMT+13:00) Samoa", "offset": "+13:00"},
    {"value": "Tokelau Is.", "label": "(GMT+13:00) Tokelau Is.", "offset": "+13:00"},
]


# Maps IANA timezone names → Redmine/Rails ActiveSupport timezone names.
# Only one Rails name per IANA zone (picked the most canonical entry where
# multiple Rails zones share the same IANA zone, e.g. India has four).
IANA_TO_REDMINE_TZ: dict[str, str] = {
    "Etc/GMT+12":               "International Date Line West",
    "Pacific/Pago_Pago":        "American Samoa",
    "Pacific/Midway":           "Midway Island",
    "Pacific/Honolulu":         "Hawaii",
    "America/Juneau":           "Alaska",
    "America/Los_Angeles":      "Pacific Time (US & Canada)",
    "America/Tijuana":          "Tijuana",
    "America/Phoenix":          "Arizona",
    "America/Mazatlan":         "Mazatlan",
    "America/Denver":           "Mountain Time (US & Canada)",
    "America/Guatemala":        "Central America",
    "America/Chicago":          "Central Time (US & Canada)",
    "America/Chihuahua":        "Chihuahua",
    "America/Mexico_City":      "Mexico City",
    "America/Monterrey":        "Monterrey",
    "America/Regina":           "Saskatchewan",
    "America/Bogota":           "Bogota",
    "America/New_York":         "Eastern Time (US & Canada)",
    "America/Indiana/Indianapolis": "Indiana (East)",
    "America/Lima":             "Lima",
    "America/Halifax":          "Atlantic Time (Canada)",
    "America/Caracas":          "Caracas",
    "America/Guyana":           "Georgetown",
    "America/La_Paz":           "La Paz",
    "America/Puerto_Rico":      "Puerto Rico",
    "America/Santiago":         "Santiago",
    "America/St_Johns":         "Newfoundland",
    "America/Sao_Paulo":        "Brasilia",
    "America/Argentina/Buenos_Aires": "Buenos Aires",
    "America/Montevideo":       "Montevideo",
    "America/Godthab":          "Greenland",
    "Atlantic/South_Georgia":   "Mid-Atlantic",
    "Atlantic/Azores":          "Azores",
    "Atlantic/Cape_Verde":      "Cape Verde Is.",
    "Europe/Edinburgh":         "Edinburgh",
    "Europe/Lisbon":            "Lisbon",
    "Europe/London":            "London",
    "Africa/Monrovia":          "Monrovia",
    "UTC":                      "UTC",
    "Etc/UTC":                  "UTC",
    "Europe/Amsterdam":         "Amsterdam",
    "Europe/Belgrade":          "Belgrade",
    "Europe/Berlin":            "Berlin",
    "Europe/Bratislava":        "Bratislava",
    "Europe/Brussels":          "Brussels",
    "Europe/Budapest":          "Budapest",
    "Africa/Casablanca":        "Casablanca",
    "Europe/Copenhagen":        "Copenhagen",
    "Europe/Dublin":            "Dublin",
    "Europe/Ljubljana":         "Ljubljana",
    "Europe/Madrid":            "Madrid",
    "Europe/Paris":             "Paris",
    "Europe/Prague":            "Prague",
    "Europe/Rome":              "Rome",
    "Europe/Sarajevo":          "Sarajevo",
    "Europe/Skopje":            "Skopje",
    "Europe/Stockholm":         "Stockholm",
    "Europe/Vienna":            "Vienna",
    "Europe/Warsaw":            "Warsaw",
    "Africa/Lagos":             "West Central Africa",
    "Europe/Zagreb":            "Zagreb",
    "Europe/Zurich":            "Zurich",
    "Europe/Athens":            "Athens",
    "Europe/Bucharest":         "Bucharest",
    "Africa/Cairo":             "Cairo",
    "Africa/Harare":            "Harare",
    "Europe/Helsinki":          "Helsinki",
    "Asia/Jerusalem":           "Jerusalem",
    "Europe/Kaliningrad":       "Kaliningrad",
    "Europe/Kiev":              "Kyiv",
    "Africa/Johannesburg":      "Pretoria",
    "Europe/Riga":              "Riga",
    "Europe/Sofia":             "Sofia",
    "Europe/Tallinn":           "Tallinn",
    "Europe/Vilnius":           "Vilnius",
    "Asia/Baghdad":             "Baghdad",
    "Europe/Istanbul":          "Istanbul",
    "Asia/Kuwait":              "Kuwait",
    "Europe/Minsk":             "Minsk",
    "Europe/Moscow":            "Moscow",
    "Africa/Nairobi":           "Nairobi",
    "Asia/Riyadh":              "Riyadh",
    "Asia/Tehran":              "Tehran",
    "Asia/Dubai":               "Abu Dhabi",
    "Asia/Baku":                "Baku",
    "Asia/Muscat":              "Muscat",
    "Europe/Samara":            "Samara",
    "Asia/Tbilisi":             "Tbilisi",
    "Asia/Yerevan":             "Yerevan",
    "Asia/Kabul":               "Kabul",
    "Asia/Almaty":              "Almaty",
    "Asia/Yekaterinburg":       "Ekaterinburg",
    "Asia/Karachi":             "Karachi",
    "Asia/Tashkent":            "Tashkent",
    "Asia/Kolkata":             "Kolkata",
    "Asia/Colombo":             "Sri Jayawardenepura",
    "Asia/Kathmandu":           "Kathmandu",
    "Asia/Dhaka":               "Dhaka",
    "Asia/Urumqi":              "Urumqi",
    "Asia/Rangoon":             "Rangoon",
    "Asia/Bangkok":             "Bangkok",
    "Asia/Ho_Chi_Minh":         "Hanoi",
    "Asia/Jakarta":             "Jakarta",
    "Asia/Krasnoyarsk":         "Krasnoyarsk",
    "Asia/Novosibirsk":         "Novosibirsk",
    "Asia/Shanghai":            "Beijing",
    "Asia/Chongqing":           "Chongqing",
    "Asia/Hong_Kong":           "Hong Kong",
    "Asia/Irkutsk":             "Irkutsk",
    "Asia/Kuala_Lumpur":        "Kuala Lumpur",
    "Australia/Perth":          "Perth",
    "Asia/Singapore":           "Singapore",
    "Asia/Taipei":              "Taipei",
    "Asia/Ulaanbaatar":         "Ulaanbaatar",
    "Asia/Tokyo":               "Tokyo",
    "Asia/Seoul":               "Seoul",
    "Asia/Yakutsk":             "Yakutsk",
    "Australia/Adelaide":       "Adelaide",
    "Australia/Darwin":         "Darwin",
    "Australia/Brisbane":       "Brisbane",
    "Australia/Sydney":         "Sydney",
    "Pacific/Guam":             "Guam",
    "Australia/Hobart":         "Hobart",
    "Pacific/Port_Moresby":     "Port Moresby",
    "Asia/Vladivostok":         "Vladivostok",
    "Asia/Magadan":             "Magadan",
    "Pacific/Noumea":           "New Caledonia",
    "Pacific/Guadalcanal":      "Solomon Is.",
    "Asia/Srednekolymsk":       "Srednekolymsk",
    "Pacific/Auckland":         "Auckland",
    "Pacific/Fiji":             "Fiji",
    "Asia/Kamchatka":           "Kamchatka",
    "Pacific/Majuro":           "Marshall Is.",
    "Pacific/Chatham":          "Chatham Is.",
    "Pacific/Tongatapu":        "Nuku'alofa",
    "Pacific/Apia":             "Samoa",
    "Pacific/Fakaofo":          "Tokelau Is.",
}


# Reverse mapping: Redmine/Rails ActiveSupport timezone names → IANA timezone names.
# Mirrors ActiveSupport::TimeZone::MAPPING from Rails.
REDMINE_TO_IANA_TZ: dict[str, str] = {
    "International Date Line West": "Etc/GMT+12",
    "Midway Island": "Pacific/Midway",
    "American Samoa": "Pacific/Pago_Pago",
    "Hawaii": "Pacific/Honolulu",
    "Alaska": "America/Juneau",
    "Pacific Time (US & Canada)": "America/Los_Angeles",
    "Tijuana": "America/Tijuana",
    "Mountain Time (US & Canada)": "America/Denver",
    "Arizona": "America/Phoenix",
    "Chihuahua": "America/Chihuahua",
    "Mazatlan": "America/Mazatlan",
    "Central Time (US & Canada)": "America/Chicago",
    "Saskatchewan": "America/Regina",
    "Guadalajara": "America/Mexico_City",
    "Mexico City": "America/Mexico_City",
    "Monterrey": "America/Monterrey",
    "Central America": "America/Guatemala",
    "Eastern Time (US & Canada)": "America/New_York",
    "Indiana (East)": "America/Indiana/Indianapolis",
    "Bogota": "America/Bogota",
    "Lima": "America/Lima",
    "Quito": "America/Lima",
    "Atlantic Time (Canada)": "America/Halifax",
    "Caracas": "America/Caracas",
    "La Paz": "America/La_Paz",
    "Santiago": "America/Santiago",
    "Newfoundland": "America/St_Johns",
    "Brasilia": "America/Sao_Paulo",
    "Buenos Aires": "America/Argentina/Buenos_Aires",
    "Montevideo": "America/Montevideo",
    "Georgetown": "America/Guyana",
    "Puerto Rico": "America/Puerto_Rico",
    "Greenland": "America/Nuuk",
    "Mid-Atlantic": "Atlantic/South_Georgia",
    "Azores": "Atlantic/Azores",
    "Cape Verde Is.": "Atlantic/Cape_Verde",
    "Dublin": "Europe/Dublin",
    "Edinburgh": "Europe/London",
    "Lisbon": "Europe/Lisbon",
    "London": "Europe/London",
    "Casablanca": "Africa/Casablanca",
    "Monrovia": "Africa/Monrovia",
    "UTC": "Etc/UTC",
    "Belgrade": "Europe/Belgrade",
    "Bratislava": "Europe/Bratislava",
    "Budapest": "Europe/Budapest",
    "Ljubljana": "Europe/Ljubljana",
    "Prague": "Europe/Prague",
    "Sarajevo": "Europe/Sarajevo",
    "Skopje": "Europe/Skopje",
    "Warsaw": "Europe/Warsaw",
    "Zagreb": "Europe/Zagreb",
    "Brussels": "Europe/Brussels",
    "Copenhagen": "Europe/Copenhagen",
    "Madrid": "Europe/Madrid",
    "Paris": "Europe/Paris",
    "Amsterdam": "Europe/Amsterdam",
    "Berlin": "Europe/Berlin",
    "Bern": "Europe/Zurich",
    "Zurich": "Europe/Zurich",
    "Rome": "Europe/Rome",
    "Stockholm": "Europe/Stockholm",
    "Vienna": "Europe/Vienna",
    "West Central Africa": "Africa/Algiers",
    "Bucharest": "Europe/Bucharest",
    "Cairo": "Africa/Cairo",
    "Helsinki": "Europe/Helsinki",
    "Kyiv": "Europe/Kyiv",
    "Riga": "Europe/Riga",
    "Sofia": "Europe/Sofia",
    "Tallinn": "Europe/Tallinn",
    "Vilnius": "Europe/Vilnius",
    "Athens": "Europe/Athens",
    "Istanbul": "Europe/Istanbul",
    "Minsk": "Europe/Minsk",
    "Jerusalem": "Asia/Jerusalem",
    "Harare": "Africa/Harare",
    "Pretoria": "Africa/Johannesburg",
    "Kaliningrad": "Europe/Kaliningrad",
    "Moscow": "Europe/Moscow",
    "St. Petersburg": "Europe/Moscow",
    "Volgograd": "Europe/Volgograd",
    "Samara": "Europe/Samara",
    "Kuwait": "Asia/Kuwait",
    "Riyadh": "Asia/Riyadh",
    "Nairobi": "Africa/Nairobi",
    "Baghdad": "Asia/Baghdad",
    "Tehran": "Asia/Tehran",
    "Abu Dhabi": "Asia/Muscat",
    "Muscat": "Asia/Muscat",
    "Baku": "Asia/Baku",
    "Tbilisi": "Asia/Tbilisi",
    "Yerevan": "Asia/Yerevan",
    "Kabul": "Asia/Kabul",
    "Ekaterinburg": "Asia/Yekaterinburg",
    "Islamabad": "Asia/Karachi",
    "Karachi": "Asia/Karachi",
    "Tashkent": "Asia/Tashkent",
    "Chennai": "Asia/Kolkata",
    "Kolkata": "Asia/Kolkata",
    "Mumbai": "Asia/Kolkata",
    "New Delhi": "Asia/Kolkata",
    "Kathmandu": "Asia/Kathmandu",
    "Dhaka": "Asia/Dhaka",
    "Sri Jayawardenepura": "Asia/Colombo",
    "Almaty": "Asia/Almaty",
    "Astana": "Asia/Almaty",
    "Novosibirsk": "Asia/Novosibirsk",
    "Rangoon": "Asia/Yangon",
    "Bangkok": "Asia/Bangkok",
    "Hanoi": "Asia/Bangkok",
    "Jakarta": "Asia/Jakarta",
    "Krasnoyarsk": "Asia/Krasnoyarsk",
    "Beijing": "Asia/Shanghai",
    "Chongqing": "Asia/Chongqing",
    "Hong Kong": "Asia/Hong_Kong",
    "Urumqi": "Asia/Urumqi",
    "Kuala Lumpur": "Asia/Kuala_Lumpur",
    "Singapore": "Asia/Singapore",
    "Taipei": "Asia/Taipei",
    "Perth": "Australia/Perth",
    "Irkutsk": "Asia/Irkutsk",
    "Ulaanbaatar": "Asia/Ulaanbaatar",
    "Seoul": "Asia/Seoul",
    "Osaka": "Asia/Tokyo",
    "Sapporo": "Asia/Tokyo",
    "Tokyo": "Asia/Tokyo",
    "Yakutsk": "Asia/Yakutsk",
    "Darwin": "Australia/Darwin",
    "Adelaide": "Australia/Adelaide",
    "Canberra": "Australia/Canberra",
    "Melbourne": "Australia/Melbourne",
    "Sydney": "Australia/Sydney",
    "Brisbane": "Australia/Brisbane",
    "Hobart": "Australia/Hobart",
    "Vladivostok": "Asia/Vladivostok",
    "Guam": "Pacific/Guam",
    "Port Moresby": "Pacific/Port_Moresby",
    "Magadan": "Asia/Magadan",
    "Srednekolymsk": "Asia/Srednekolymsk",
    "Solomon Is.": "Pacific/Guadalcanal",
    "New Caledonia": "Pacific/Noumea",
    "Fiji": "Pacific/Fiji",
    "Kamchatka": "Asia/Kamchatka",
    "Marshall Is.": "Pacific/Majuro",
    "Auckland": "Pacific/Auckland",
    "Wellington": "Pacific/Auckland",
    "Nuku'alofa": "Pacific/Tongatapu",
    "Tokelau Is.": "Pacific/Fakaofo",
    "Chatham Is.": "Pacific/Chatham",
    "Samoa": "Pacific/Apia",
}


def iana_to_redmine_tz(iana_tz: str) -> str:
    """
    Converts an IANA timezone name to a Redmine/Rails ActiveSupport timezone name.
    Falls back to "UTC" if the IANA name is not found in the mapping.
    """
    result = IANA_TO_REDMINE_TZ.get(iana_tz)
    if result is None:
        logger.warning(f"Unknown IANA timezone '{iana_tz}', falling back to UTC for Redmine.")
        result = "UTC"
    return result